[toolchain]
channel = "nightly-2023-04-12"
components = ["rustc-dev"]

# You are probably looking at this because you got an error that the toolchain
# that was configured does not exist,
#
# This is by design. To run this tool you need a patched, source compiled
# version of rust. Once you have created it, you should create "rust-dfpp-patch"
# as a symlink to the patched stage2 compiler.
# 
# For detailed instructions see https://www.notion.so/justus-adam/Patched-Toolchain-Installation-bbd2098048ef4b08a1b6f3bbf03d4c8b
#path = "rust-dfpp-patch"